# Generated by Django 6.0.7 on 2026-10-07 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Days the budget has to cover (e.g. 22 working days). Blank means the full month.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
